services:
  whatsupdocker:
    container_name: whats-up-docker
    environment:
      TZ: Europe/Berlin
      WUD_AUTH_OIDC_AUTHENTIK_CLIENTID: ${PORTAINER_WUD_CLIENT_ID}
      WUD_AUTH_OIDC_AUTHENTIK_CLIENTSECRET: ${PORTAINER_WUD_CLIENT_SECRET}
      WUD_AUTH_OIDC_AUTHENTIK_DISCOVERY: https://id.bodkys.house/application/o/whats-up-docker/.well-known/openid-configuration
      WUD_WATCHER_olympus_SOCKET: /var/run/docker.sock
      WUD_WATCHER_pandora_HOST: pandora.bodkys.house
      WUD_WATCHER_pandora_CAFILE: /certs/ca.pem
      WUD_WATCHER_pandora_CERTFILE: /certs/wud.pem
      WUD_WATCHER_pandora_KEYFILE: /certs/wud.key
      WUD_WATCHER_pandora_PORT: 2376
    image: getwud/wud:8.0.1
    labels:
      traefik.docker.network: traefik_traefik
      traefik.enable: true
      traefik.http.routers.wud.entrypoints: websecure
      traefik.http.routers.wud.rule: Host(`wud.bodkys.house`)
      traefik.http.routers.wud.service: wud
      traefik.http.routers.wud.tls.certResolver: civo
      traefik.http.routers.wud.tls.domains.0.main: wud.bodkys.house
      traefik.http.services.wud.loadbalancer.server.port: 3000
      wud.link.template: https://github.com/getwud/wud/releases/tag/$${transformed}
      wud.tag.include: ^\d+\.\d+\.\d+$$
    networks:
      - traefik_traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/wud:/certs/

networks:
  traefik_traefik:
    external: true
