services:
  homarr:
    container_name: homarr
    dns:
      - 192.168.1.3
      - 1.1.1.1
      - 8.8.8.8
    environment:
      ADMIN_GROUP: homarr-admins
      AUTH_DOMAIN: id.bodkys.house
      AUTH_LOGOUT_REDIRECT_URL: https://id.bodkys.house/application/o/homarr/end-session/
      AUTH_OIDC_AUTO_LOGIN: true
      AUTH_OIDC_CLIENT_ID: ${PORTAINER_OIDC_ID}
      AUTH_OIDC_CLIENT_NAME: authentik
      AUTH_OIDC_CLIENT_SECRET: ${PORTAINER_OIDC_SECRET}
      AUTH_OIDC_GROUPS_ATTRIBUTE: groups
      AUTH_OIDC_ISSUER: https://id.bodkys.house/application/o/homarr/
      AUTH_OIDC_SCOPE_OVERWRITE: openid email profile groups
      AUTH_OIDC_URI: https://id.bodkys.house/application/o/authorize
      AUTH_PROVIDERS: oidc
      BASE_URL: https://home.bodkys.house
      HOMARR_FQDN: home.bodkys.house
      NEXTAUTH_URL: https://home.bodkys.house
      OIDC_CLIENT_ID: ${PORTAINER_OIDC_ID}
      OIDC_CLIENT_SECRET: ${PORTAINER_OIDC_SECRET}
      OIDC_SLUG: homarr
      SECRET_ENCRYPTION_KEY: ${PORTAINER_ENCRYPTION_KEY}
      TZ: Europe/Berlin
    image: ghcr.io/homarr-labs/homarr:v1.30.1
    labels:
      traefik.docker.network: traefik_traefik
      traefik.enable: true
      traefik.http.routers.homarr.entrypoints: websecure
      traefik.http.routers.homarr.rule: Host(`home.bodkys.house`)
      traefik.http.routers.homarr.service: homarr
      traefik.http.routers.homarr.tls.certResolver: civo
      traefik.http.routers.homarr.tls.domains.0.main: home.bodkys.house
      traefik.http.services.homarr.loadbalancer.server.port: 7575 
      wud.link.template: https://github.com/homarr-labs/homarr/releases/tag/$${transformed}
      wud.tag.include: ^v\d+\.\d+\.\d+$$
    networks:
      - traefik_traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - homarr_data:/appdata

networks:
  traefik_traefik:
    external: true

volumes:
  homarr_data: {}
