services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.55
    labels:
      traefik.enable: true
      traefik.http.routers.adguard.entrypoints: websecure
      traefik.http.routers.adguard.rule: Host(`adguard.bodkys.house`)
      traefik.http.routers.adguard.service: adguard
      traefik.http.routers.adguard.tls.certResolver: civo
      traefik.http.routers.adguard.tls.domains.0.main: adguard.bodkys.house
      traefik.http.services.adguard.loadbalancer.server.port: 80
      wud.tag.include: ^v\d+\.\d+\.\d+$$
    networks:
      - traefik_traefik
    ports:
      - 192.168.1.3:53:53/udp # https://stackoverflow.com/questions/64007727/docker-compose-internal-dns-server-127-0-0-11-connection-refused
    restart: always
    volumes:
      - adguard_workdir:/opt/adguardhome/work
      - adguard_confdir:/opt/adguardhome/conf

networks:
  traefik_traefik:
    external: true

volumes:
  adguard_workdir: {}
  adguard_confdir: {}
