services:
  minecraft:
    environment:
      CF_API_KEY: ${PORTAINER_CURSEFORGE_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4
      ENABLE_ROLLING_LOGS: "true"
      EULA: "true"
      LEVEL: "better-mc"
      LOG_TIMESTAMP: "true"
      MEMORY: 8G
      MOTD: "Willkommen zu BetterMC :)"
      PLAYER_IDLE_TIMEOUT: "10"
      RCON_CMDS_FIRST_CONNECT: |-
        pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        pregen start 200
      RCON_CMDS_ON_DISCONNECT: |-
        gamerule doFireTick true
      RCON_CMDS_STARTUP: |-
        pregen start 200
      TYPE: AUTO_CURSEFORGE
      VIEW_DISTANCE: "20"
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
    volumes:
      - data:/data

volumes:
  data: {}
