services:
  minecraft:
    environment:
      ENABLE_ROLLING_LOGS: "true"
      EULA: "true"
      LEVEL: "server-world"
      LOG_TIMESTAMP: "true"
      MEMORY: 6G
      OPS: |-
        Trix213
      PLAYER_IDLE_TIMEOUT: "10"
      TYPE: FORGE
      VERSION: 1.20.1
      VIEW_DISTANCE: "20"
    image: itzg/minecraft-server:java21
    ports:
      - 25565:25565
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - vanilla-data:/data

volumes:
  vanilla-data: {}
