services:
  minecraft:
    environment:
      ENABLE_ROLLING_LOGS: "true"
      ENABLE_WHITELIST: "true"
      EULA: "true"
      LEVEL: "server-world"
      LOG_TIMESTAMP: "true"
      MEMORY: 10G
      OPS: |-
        Excaaliibur
        SirPigley
        DeltaP
        IDomDomI
        Cooksalt
        Honigmond27
        DieFaule
        KanonenGurke
        Tobiwan_99
        Trix213
        Snegge5
        pfief
      PLAYER_IDLE_TIMEOUT: "10"
      TYPE: FORGE
      VERSION: 1.20.1
      VIEW_DISTANCE: "20"
      WHITELIST: "Excaaliibur,SirPigley,DeltaP,IDomDomI,Cooksalt,Honigmond27,DieFaule,KanonenGurke,Tobiwan_99,Trix213,Snegge5,pfief"
    image: itzg/minecraft-server:java21
    labels:
      wud.watch: false
    ports:
      - 25565:25565
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - vanilla-data:/data

volumes:
  vanilla-data: {}
