services:
  minecraft:
    environment:
      ENABLE_ROLLING_LOGS: "true"
      EULA: "true"
      LEVEL: "server-world"
      LOG_TIMESTAMP: "true"
      MEMORY: 6G
      OPS: |-
        Trix213
      PLAYER_IDLE_TIMEOUT: "10"
      RCON_CMDS_FIRST_CONNECT: |-
        pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        pregen start 200
      RCON_CMDS_ON_DISCONNECT: |-
        gamerule doFireTick true
      RCON_CMDS_STARTUP: |-
        pregen start 200
      TYPE: FABRIC
      VIEW_DISTANCE: "20"
    image: itzg/minecraft-server:java21
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
    volumes:
      - vanilla-data:/data

volumes:
  vanilla-data: {}
