name: omni
services:
  omni:
    command: >
      --account-id=$${PORTAINER_OMNI_ACCOUNT_UUID}
      --advertised-api-url=https://omni.bodkys.house/
      --advertised-kubernetes-proxy-url=https://kube.omni.bodkys.house/
      --auth-saml-enabled=true
      --auth-saml-metadata=https://id.bodkys.house/api/v3/providers/saml/5/metadata/?download
      --bind-addr=127.0.0.1:8080
      --k8s-proxy-bind-addr=127.0.0.1:8100
      --machine-api-bind-addr=127.0.0.1:8090
      --name=Omni
      --private-key-source=/run/secrets/omni_private_key
      --siderolink-api-advertised-url=https://api.omni.bodkys.house:443/
      --siderolink-use-grpc-tunnel=true
    container_name: omni
    image: "ghcr.io/siderolabs/omni:v0.46.1"
    #devices:
    #  - /dev/net/tun
    labels:
      traefik.docker.network: traefik_traefik
      traefik.enable: true
      traefik.http.routers.api_omni.entrypoints: websecure
      traefik.http.routers.api_omni.rule: Host(`api.omni.bodkys.house`)
      traefik.http.routers.api_omni.service: api_omni
      traefik.http.routers.kube_omni.entrypoints: websecure
      traefik.http.routers.kube_omni.rule: Host(`kube.omni.bodkys.house`)
      traefik.http.routers.kube_omni.service: kube_omni
      traefik.http.routers.omni.entrypoints: websecure
      traefik.http.routers.omni.rule: Host(`omni.bodkys.house`)
      traefik.http.routers.omni.service: omni
      traefik.http.routers.omni.tls.certResolver: civo
      traefik.http.routers.omni.tls.domains.0.main: omni.bodkys.house
      traefik.http.routers.omni.tls.domains.sans.0: api.omni.bodkys.house
      traefik.http.routers.omni.tls.domains.sans.1: kube.omni.bodkys.house
      traefik.http.services.kube_omni.loadbalancer.server.port: 8100
      traefik.http.services.omni.loadbalancer.server.port: 8080
      traefik.http.services.api_omni.loadbalancer.server.port: 8090
      wud.link.template: https://github.com/siderolabs/omni/releases/tag/$${transformed}
      wud.tag.include: ^v\d+\.\d+\.\d+$$
    networks:
      - traefik
    restart: unless-stopped
    secrets:
      - omni_private_key
    volumes:
      - omni_etcd:/_out/etcd

networks:
  traefik: {}

secrets:
  omni_private_key:
    environment: PORTAINER_OMNI_PRIVATE_KEY

volumes:
  omni_etcd: {}
