machine:
  kubelet:
    extraArgs:
      rotate-server-certificates: true
  
  network:
    nameservers:
      - 192.168.1.3
    extraHostEntries:
      - ip: 192.168.1.11
        aliases:
          - talos1
          - talos1.bodkys.house
          - talos.bodkys.house
      - ip: 192.168.1.12
        aliases:
          - talos2
          - talos2.bodkys.house
          - talos.bodkys.house
      - ip: 192.168.1.13
        aliases:
          - talos3
          - talos3.bodkys.house
          - talos.bodkys.house
      - ip: 192.168.1.14
        aliases:
          - talos4
          - talos4.bodkys.house
    kubespan:
      enabled: false
  
  install:
    disk: /dev/mmcblk0

  features:
    kubePrism:
      enabled: true
---

apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn
provisioning:
  diskSelector:
    match: disk.transport == 'nvme'
  minSize: 500Gi
  grow: true
