services:
  prometheus:
    command: ['--log.level=debug', '--config.file=/etc/prometheus/prometheus.yml']
    container_name: prometheus
    image: prom/prometheus:v3.2.0
    labels:
      traefik.docker.network: traefik_traefik
      traefik.enable: true
      traefik.http.routers.prometheus-svc.entrypoints: websecure
      traefik.http.routers.prometheus-svc.rule: Host(`prometheus.bodkys.house`)
      traefik.http.routers.prometheus-svc.service: prometheus-svc
      traefik.http.routers.prometheus-svc.tls.certResolver: civo
      traefik.http.routers.prometheus-svc.tls.domains.0.main: prometheus.bodkys.house
      traefik.http.services.prometheus-svc.loadbalancer.server.port: 9090
      wud.link.template: https://github.com/prometheus/prometheus/releases/tag/$${transformed}
      wud.tag.include: ^v\d+\.\d+\.\d+$$
    networks:
      - traefik_traefik
    restart: unless-stopped
    secrets:
      - grafana_password
      - grafana_username
      - oauth_secret
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  traefik_traefik:
    external: true

secrets:
  grafana_password:
    environment: PORTAINER_GRAFANA_CLOUD_PASSWORD
  grafana_username:
    environment: PORTAINER_GRAFANA_CLOUD_USERNAME
  oauth_secret:
    environment: PORTAINER_OAUTH_SECRET
