global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username_file: /run/secrets/grafana_username 
      password_file: /run/secrets/grafana_password
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
