global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username_file: /run/secrets/grafana_username 
      password_file: /run/secrets/grafana_password
    name: Grafana Cloud
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: whats-up-docker
    scheme: https
    oauth2:
      client_id: 84X6Jkgwwt0gotFpKFEY6ws95Ehig9kpUZUiJJ5Q
      client_secret_file: /run/secrets/oauth_secret
      endpoint_params:
        grant_type: client_credentials    
        scope: openid profile email
      token_url: https://id.bodkys.house/application/o/token/
    static_configs:
      - targets: ["wud.bodkys.house"]
    metric_relabel_configs:
      - source_labels:
          - __name__
        regex: "wud_.*"
        action: keep
